apiVersion: v1
kind: Service
metadata: 
  name: clusterip-svc
  labels: 
    env: demo-service
spec: 
  type: ClusterIP
  ports: 
  - port: 80
    targetPort: 80
  selector: 
    env: demo # It will also have a selecter. Which will select deployments to be exposed as service.